name: Dev Build

on:
  push:
    branches: [ main ]
    paths: [ src/**, pom.xml, .github/workflows/publish.yml ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: 'Create settings.xml'
        uses: s4u/maven-settings-action@v2.8.0
        with:
          githubServer: false
          servers: '[{"id": "ossrh", "username": "Travja", "password": "${{ secrets.SONATYPE_DEPLOY_KEY }}"}]'
#      - name: Build with Maven
#        run: mvn clean package -e
#        env:
#          GITHUB_TOKEN_REF: ${{ secrets.GH_PAT_FOR_ACTIONS_TOKEN }}
      - name: Publish to Maven Central
        id: publish-maven
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          mvn clean deploy -P gpg,publish -DcreateChecksum=true 2>&1 | tee log.txt
          result_code=${PIPESTATUS[0]}
          exit $result_code
#      - name: Publish artifact on GitHub Packages
#        run: mvn clean deploy -e -DskipTests
#        env:
#          GITHUB_TOKEN: ${{ secrets.DEPLOY_KEY }}
      - name: Notify Discord
        run: pip install simplejson && python ./.github/notify_published.py ${{ secrets.BSP_WEBHOOK }}
